version: '2'
services:
    hostings_local:
        build:
            context: ./
            dockerfile: hostings_local.dockerfile
        volumes:
            - ./public:/app
        ports:
          - '9003:8000'