---
version: 2
jobs:
  output_pdf:
    working_directory: ~/yamacraft-cv
    machine: true
    enviroment:
      - FIREBASE_TOKEN
    steps:
      - checkout
      - run:
          name: PDF output
          command: |
            docker-compose -f ./output-compose.yml up --build
      - save_cache:
          key: deploy-{{ epoch }}
          paths:
            - ~/yamacraft-cv
  deploy:
    working_directory: ~/yamacraft-cv
    machine: true
    steps:
      - restore_cache:
          keys:
            - deploy
      - run:
          name: deploy
          command: |
            docker-compose -f ./deploy-compose.yml up --build
workflows:
  version: 2
  deploy_hosting:
    jobs:
      - output_pdf:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - output_pdf
...