name: Output and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm install

      - name: Install noto
        run: sudo apt-get update -y && sudo apt-get install -y fonts-noto
      
      - name: PDF Output
        run: ./node_modules/.bin/markdown-pdf cv.md -s pdf.css -o public/cv.pdf

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ vars.FIREBASE_TOKEN }}

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: yamacraft-cv
          path: public

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: yamacraft-cv deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()